import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class'],
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.{vue,js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                serif: ['Noto Serif', ...defaultTheme.fontFamily.serif],
            },
            colors: {
                'on-tertiary-fixed': '#241432',
                'on-primary-fixed-variant': '#49491d',
                'on-tertiary-fixed-variant': '#524060',
                'on-error-container': '#93000a',
                'on-secondary-fixed-variant': '#484833',
                'secondary-container': '#e6e4c8',
                'inverse-on-surface': '#f1f1ec',
                outline: '#79776a',
                'tertiary-container': '#7a6689',
                background: '#fafaf4',
                'surface-container-highest': '#e3e3de',
                'surface-tint': '#616132',
                'on-background': '#1a1c19',
                'tertiary-fixed': '#f1daff',
                'on-tertiary': '#ffffff',
                'surface-container-lowest': '#ffffff',
                'outline-variant': '#c9c7b8',
                'surface-dim': '#dadad5',
                'surface-container': '#eeeee9',
                'surface-variant': '#e3e3de',
                'tertiary-fixed-dim': '#d6bee5',
                'on-tertiary-container': '#faedff',
                'on-surface-variant': '#48473c',
                secondary: '#605f49',
                'on-secondary-container': '#66654f',
                'error-container': '#ffdad6',
                'primary-fixed': '#e7e6ab',
                'on-primary': '#ffffff',
                'primary-fixed-dim': '#caca91',
                'surface-container-low': '#f4f4ee',
                'surface-bright': '#fafaf4',
                'on-error': '#ffffff',
                'secondary-fixed': '#e6e4c8',
                'secondary-fixed-dim': '#cac8ad',
                'on-secondary': '#ffffff',
                tertiary: '#614e70',
                'on-primary-fixed': '#1d1d00',
                'inverse-primary': '#caca91',
                'surface-container-high': '#e8e8e3',
                'inverse-surface': '#2f312e',
                'primary-container': '#707040',
                'on-primary-container': '#f5f4b9',
                'on-surface': '#1a1c19',
                primary: '#57572a',
                error: '#ba1a1a',
                'on-secondary-fixed': '#1c1c0b',
                surface: '#fafaf4',
            },
            borderRadius: {
                lg: '0.75rem',
                md: '0.5rem',
                sm: '0.25rem',
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
};
